# DEPLOY_TARGET: openshift
# BUILD_ARCH: amd64
FROM registry.access.redhat.com/ubi9/nodejs-20 AS builder
WORKDIR /opt/app-root/src
COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build

FROM registry.access.redhat.com/ubi9/nginx-124
COPY --from=builder /opt/app-root/src/dist /usr/share/nginx/html
EXPOSE 8080
